import { Factory, Configuration } from './types';

export const defaultFactory: Factory = {
  id: 'factory-1',
  name: 'Automotive Manufacturing Complex',
  width: 2000,
  height: 3000,
  gridUnit: 100,
  areas: [
    {
      id: 'area-1',
      areaId: 'AREA-01',
      areaName: 'Floor Left (Inbound & Raw)',
      x: 0,
      y: 0,
      width: 850,
      height: 650,
      imageUrl: '',
      lines: [
        {
          id: 'line-1-1',
          lineId: 'LINE-01-01',
          lineName: 'Receiving Line',
          x: 50,
          y: 50,
          width: 350,
          height: 200,
          workCenters: [
            {
              id: 'wc-1-1-1',
              workCenterId: 'WC-01-01-01',
              machineName: 'Dock Receiver 1',
              x: 50,
              y: 50,
              width: 80,
              height: 80,
              icon: 'package',
              status: 'operational',
            },
            {
              id: 'wc-1-1-2',
              workCenterId: 'WC-01-01-02',
              machineName: 'Quality Inspector',
              x: 150,
              y: 50,
              width: 80,
              height: 80,
              icon: 'shield-check',
              status: 'operational',
            },
            {
              id: 'wc-1-1-3',
              workCenterId: 'WC-01-01-03',
              machineName: 'Dock Receiver 2',
              x: 250,
              y: 50,
              width: 80,
              height: 80,
              icon: 'package',
              status: 'idle',
            },
          ],
          color: '#E8F5E9',
        },
        {
          id: 'line-1-2',
          lineId: 'LINE-01-02',
          lineName: 'Kitting Line',
          x: 50,
          y: 300,
          width: 350,
          height: 200,
          workCenters: [
            {
              id: 'wc-1-2-1',
              workCenterId: 'WC-01-02-01',
              machineName: 'Kitting Station 1',
              x: 50,
              y: 300,
              width: 80,
              height: 80,
              icon: 'boxes',
              status: 'operational',
            },
            {
              id: 'wc-1-2-2',
              workCenterId: 'WC-01-02-02',
              machineName: 'Kitting Station 2',
              x: 150,
              y: 300,
              width: 80,
              height: 80,
              icon: 'boxes',
              status: 'operational',
            },
            {
              id: 'wc-1-2-3',
              workCenterId: 'WC-01-02-03',
              machineName: 'Barcode Scanner',
              x: 250,
              y: 300,
              width: 80,
              height: 80,
              icon: 'barcode',
              status: 'operational',
            },
          ],
          color: '#F3E5F5',
        },
      ],
      buffers: [
        {
          id: 'buf-1-1',
          bufferId: 'BUF-01-01',
          bufferName: 'Receiving Buffer',
          x: 450,
          y: 50,
          width: 150,
          height: 120,
          capacity: 100,
          currentLevel: 45,
        },
        {
          id: 'buf-1-2',
          bufferId: 'BUF-01-02',
          bufferName: 'Kitting Buffer',
          x: 450,
          y: 300,
          width: 150,
          height: 120,
          capacity: 80,
          currentLevel: 62,
        },
      ],
      storage: [
        {
          id: 'stor-1-1',
          storageId: 'STOR-01-01',
          storageName: 'Raw Material Storage A',
          x: 650,
          y: 50,
          width: 150,
          height: 200,
          type: 'racking',
        },
        {
          id: 'stor-1-2',
          storageId: 'STOR-01-02',
          storageName: 'Raw Material Storage B',
          x: 650,
          y: 300,
          width: 150,
          height: 200,
          type: 'racking',
        },
      ],
    },
    {
      id: 'area-2',
      areaId: 'AREA-02',
      areaName: 'Floor Mid (Press & Assembly)',
      x: 900,
      y: 0,
      width: 850,
      height: 650,
      imageUrl: '',
      lines: [
        {
          id: 'line-2-1',
          lineId: 'LINE-02-01',
          lineName: 'Press Line 1',
          x: 920,
          y: 50,
          width: 400,
          height: 250,
          workCenters: [
            {
              id: 'wc-2-1-1',
              workCenterId: 'WC-02-01-01',
              machineName: 'Feeder',
              x: 920,
              y: 50,
              width: 70,
              height: 70,
              icon: 'arrow-right',
              status: 'operational',
            },
            {
              id: 'wc-2-1-2',
              workCenterId: 'WC-02-01-02',
              machineName: '300T Hydraulic Press',
              x: 1010,
              y: 50,
              width: 80,
              height: 80,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-2-1-3',
              workCenterId: 'WC-02-01-03',
              machineName: 'Trim Press',
              x: 1110,
              y: 50,
              width: 80,
              height: 80,
              icon: 'scissors',
              status: 'operational',
            },
            {
              id: 'wc-2-1-4',
              workCenterId: 'WC-02-01-04',
              machineName: 'Deburr Station',
              x: 1210,
              y: 50,
              width: 80,
              height: 80,
              icon: 'file',
              status: 'maintenance',
            },
          ],
          color: '#FFF3E0',
        },
        {
          id: 'line-2-2',
          lineId: 'LINE-02-02',
          lineName: 'Press Line 2',
          x: 920,
          y: 350,
          width: 400,
          height: 250,
          workCenters: [
            {
              id: 'wc-2-2-1',
              workCenterId: 'WC-02-02-01',
              machineName: 'Feeder',
              x: 920,
              y: 350,
              width: 70,
              height: 70,
              icon: 'arrow-right',
              status: 'operational',
            },
            {
              id: 'wc-2-2-2',
              workCenterId: 'WC-02-02-02',
              machineName: '300T Hydraulic Press',
              x: 1010,
              y: 350,
              width: 80,
              height: 80,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-2-2-3',
              workCenterId: 'WC-02-02-03',
              machineName: 'Trim Press',
              x: 1110,
              y: 350,
              width: 80,
              height: 80,
              icon: 'scissors',
              status: 'operational',
            },
            {
              id: 'wc-2-2-4',
              workCenterId: 'WC-02-02-04',
              machineName: 'Vision Inspection',
              x: 1210,
              y: 350,
              width: 80,
              height: 80,
              icon: 'eye',
              status: 'operational',
            },
          ],
          color: '#FCE4EC',
        },
      ],
      buffers: [
        {
          id: 'buf-2-1',
          bufferId: 'BUF-02-01',
          bufferName: 'Pressed Parts Buffer',
          x: 1380,
          y: 100,
          width: 150,
          height: 400,
          capacity: 200,
          currentLevel: 156,
        },
      ],
      storage: [],
    },
    {
      id: 'area-3',
      areaId: 'AREA-03',
      areaName: 'Floor Right (Body & Paint)',
      x: 1800,
      y: 0,
      width: 200,
      height: 650,
      imageUrl: '',
      lines: [
        {
          id: 'line-3-1',
          lineId: 'LINE-03-01',
          lineName: 'Welding Line',
          x: 1820,
          y: 50,
          width: 160,
          height: 550,
          workCenters: [
            {
              id: 'wc-3-1-1',
              workCenterId: 'WC-03-01-01',
              machineName: 'Spot Welder 1',
              x: 1820,
              y: 50,
              width: 70,
              height: 70,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-3-1-2',
              workCenterId: 'WC-03-01-02',
              machineName: 'Spot Welder 2',
              x: 1820,
              y: 140,
              width: 70,
              height: 70,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-3-1-3',
              workCenterId: 'WC-03-01-03',
              machineName: 'Sealer Robot',
              x: 1820,
              y: 230,
              width: 70,
              height: 70,
              icon: 'activity',
              status: 'operational',
            },
            {
              id: 'wc-3-1-4',
              workCenterId: 'WC-03-01-04',
              machineName: 'Quality Gate',
              x: 1820,
              y: 320,
              width: 70,
              height: 70,
              icon: 'shield-check',
              status: 'idle',
            },
            {
              id: 'wc-3-1-5',
              workCenterId: 'WC-03-01-05',
              machineName: 'Rework Station',
              x: 1820,
              y: 410,
              width: 70,
              height: 70,
              icon: 'tool',
              status: 'down',
            },
          ],
          color: '#E0F2F1',
        },
      ],
      buffers: [],
      storage: [],
    },
    {
      id: 'area-4',
      areaId: 'AREA-04',
      areaName: 'Paint Shop',
      x: 0,
      y: 750,
      width: 850,
      height: 750,
      imageUrl: '',
      lines: [
        {
          id: 'line-4-1',
          lineId: 'LINE-04-01',
          lineName: 'Paint Line 1',
          x: 50,
          y: 800,
          width: 400,
          height: 600,
          workCenters: [
            {
              id: 'wc-4-1-1',
              workCenterId: 'WC-04-01-01',
              machineName: 'Pre-Wash Station',
              x: 50,
              y: 800,
              width: 80,
              height: 80,
              icon: 'droplets',
              status: 'operational',
            },
            {
              id: 'wc-4-1-2',
              workCenterId: 'WC-04-01-02',
              machineName: 'E-Coat Booth',
              x: 150,
              y: 800,
              width: 80,
              height: 80,
              icon: 'wind',
              status: 'operational',
            },
            {
              id: 'wc-4-1-3',
              workCenterId: 'WC-04-01-03',
              machineName: 'Primer Spray',
              x: 250,
              y: 800,
              width: 80,
              height: 80,
              icon: 'spray-can',
              status: 'operational',
            },
            {
              id: 'wc-4-1-4',
              workCenterId: 'WC-04-01-04',
              machineName: 'Base Coat Robot',
              x: 50,
              y: 920,
              width: 80,
              height: 80,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-4-1-5',
              workCenterId: 'WC-04-01-05',
              machineName: 'Clear Coat Robot',
              x: 150,
              y: 920,
              width: 80,
              height: 80,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-4-1-6',
              workCenterId: 'WC-04-01-06',
              machineName: 'Oven Cure 1',
              x: 250,
              y: 920,
              width: 80,
              height: 80,
              icon: 'flame',
              status: 'operational',
            },
            {
              id: 'wc-4-1-7',
              workCenterId: 'WC-04-01-07',
              machineName: 'Oven Cure 2',
              x: 350,
              y: 920,
              width: 80,
              height: 80,
              icon: 'flame',
              status: 'idle',
            },
            {
              id: 'wc-4-1-8',
              workCenterId: 'WC-04-01-08',
              machineName: 'Quality Inspection',
              x: 50,
              y: 1040,
              width: 80,
              height: 80,
              icon: 'eye',
              status: 'operational',
            },
          ],
          color: '#F1F8E9',
        },
      ],
      buffers: [
        {
          id: 'buf-4-1',
          bufferId: 'BUF-04-01',
          bufferName: 'Pre-Paint Buffer',
          x: 500,
          y: 800,
          width: 150,
          height: 150,
          capacity: 50,
          currentLevel: 32,
        },
        {
          id: 'buf-4-2',
          bufferId: 'BUF-04-02',
          bufferName: 'Painted Parts Buffer',
          x: 500,
          y: 1000,
          width: 150,
          height: 200,
          capacity: 100,
          currentLevel: 78,
        },
      ],
      storage: [
        {
          id: 'stor-4-1',
          storageId: 'STOR-04-01',
          storageName: 'Paint Supply',
          x: 700,
          y: 800,
          width: 120,
          height: 200,
          type: 'chemical_storage',
        },
      ],
    },
    {
      id: 'area-5',
      areaId: 'AREA-05',
      areaName: 'Trim, Chassis & Final Assembly',
      x: 900,
      y: 750,
      width: 850,
      height: 750,
      imageUrl: '',
      lines: [
        {
          id: 'line-5-1',
          lineId: 'LINE-05-01',
          lineName: 'Interior Trim Line',
          x: 920,
          y: 800,
          width: 350,
          height: 200,
          workCenters: [
            {
              id: 'wc-5-1-1',
              workCenterId: 'WC-05-01-01',
              machineName: 'Door Module Install',
              x: 920,
              y: 800,
              width: 80,
              height: 80,
              icon: 'square',
              status: 'operational',
            },
            {
              id: 'wc-5-1-2',
              workCenterId: 'WC-05-01-02',
              machineName: 'Seat Installation',
              x: 1020,
              y: 800,
              width: 80,
              height: 80,
              icon: 'armchair',
              status: 'operational',
            },
            {
              id: 'wc-5-1-3',
              workCenterId: 'WC-05-01-03',
              machineName: 'Electronics Install',
              x: 1120,
              y: 800,
              width: 80,
              height: 80,
              icon: 'cpu',
              status: 'operational',
            },
            {
              id: 'wc-5-1-4',
              workCenterId: 'WC-05-01-04',
              machineName: 'Fastener Torque',
              x: 1220,
              y: 800,
              width: 80,
              height: 80,
              icon: 'wrench',
              status: 'operational',
            },
          ],
          color: '#FFF9C4',
        },
        {
          id: 'line-5-2',
          lineId: 'LINE-05-02',
          lineName: 'Chassis Assembly Line',
          x: 920,
          y: 1040,
          width: 350,
          height: 200,
          workCenters: [
            {
              id: 'wc-5-2-1',
              workCenterId: 'WC-05-02-01',
              machineName: 'Suspension Install',
              x: 920,
              y: 1040,
              width: 80,
              height: 80,
              icon: 'tool',
              status: 'operational',
            },
            {
              id: 'wc-5-2-2',
              workCenterId: 'WC-05-02-02',
              machineName: 'Brake Bleed',
              x: 1020,
              y: 1040,
              width: 80,
              height: 80,
              icon: 'drop',
              status: 'operational',
            },
            {
              id: 'wc-5-2-3',
              workCenterId: 'WC-05-02-03',
              machineName: 'Tire Mount',
              x: 1120,
              y: 1040,
              width: 80,
              height: 80,
              icon: 'circle',
              status: 'operational',
            },
            {
              id: 'wc-5-2-4',
              workCenterId: 'WC-05-02-04',
              machineName: 'Fluid Fill',
              x: 1220,
              y: 1040,
              width: 80,
              height: 80,
              icon: 'droplets',
              status: 'operational',
            },
          ],
          color: '#E1F5FE',
        },
      ],
      buffers: [
        {
          id: 'buf-5-1',
          bufferId: 'BUF-05-01',
          bufferName: 'Assembly Buffer',
          x: 1350,
          y: 900,
          width: 150,
          height: 250,
          capacity: 120,
          currentLevel: 95,
        },
      ],
      storage: [
        {
          id: 'stor-5-1',
          storageId: 'STOR-05-01',
          storageName: 'Component Storage',
          x: 700,
          y: 900,
          width: 150,
          height: 250,
          type: 'racking',
        },
      ],
    },
    {
      id: 'area-6',
      areaId: 'AREA-06',
      areaName: 'Testing & QC (EOL)',
      x: 1800,
      y: 750,
      width: 200,
      height: 750,
      imageUrl: '',
      lines: [
        {
          id: 'line-6-1',
          lineId: 'LINE-06-01',
          lineName: 'Test Line',
          x: 1820,
          y: 800,
          width: 160,
          height: 650,
          workCenters: [
            {
              id: 'wc-6-1-1',
              workCenterId: 'WC-06-01-01',
              machineName: 'Electrical Test',
              x: 1820,
              y: 800,
              width: 70,
              height: 70,
              icon: 'zap',
              status: 'operational',
            },
            {
              id: 'wc-6-1-2',
              workCenterId: 'WC-06-01-02',
              machineName: 'Engine Dyno',
              x: 1820,
              y: 890,
              width: 70,
              height: 70,
              icon: 'bolt',
              status: 'operational',
            },
            {
              id: 'wc-6-1-3',
              workCenterId: 'WC-06-01-03',
              machineName: 'Emissions Test',
              x: 1820,
              y: 980,
              width: 70,
              height: 70,
              icon: 'wind',
              status: 'operational',
            },
            {
              id: 'wc-6-1-4',
              workCenterId: 'WC-06-01-04',
              machineName: 'Safety Inspection',
              x: 1820,
              y: 1070,
              width: 70,
              height: 70,
              icon: 'shield-alert',
              status: 'operational',
            },
            {
              id: 'wc-6-1-5',
              workCenterId: 'WC-06-01-05',
              machineName: 'Detail & Polish',
              x: 1820,
              y: 1160,
              width: 70,
              height: 70,
              icon: 'sparkles',
              status: 'operational',
            },
            {
              id: 'wc-6-1-6',
              workCenterId: 'WC-06-01-06',
              machineName: 'Final QC Gate',
              x: 1820,
              y: 1250,
              width: 70,
              height: 70,
              icon: 'check-circle',
              status: 'operational',
            },
          ],
          color: '#F0F4C3',
        },
      ],
      buffers: [],
      storage: [],
    },
    {
      id: 'area-7',
      areaId: 'AREA-07',
      areaName: 'Finished Vehicle Dispatch',
      x: 0,
      y: 1650,
      width: 2000,
      height: 1350,
      imageUrl: '',
      lines: [
        {
          id: 'line-7-1',
          lineId: 'LINE-07-01',
          lineName: 'Final Staging',
          x: 50,
          y: 1700,
          width: 450,
          height: 200,
          workCenters: [
            {
              id: 'wc-7-1-1',
              workCenterId: 'WC-07-01-01',
              machineName: 'Buffer Station',
              x: 50,
              y: 1700,
              width: 80,
              height: 80,
              icon: 'square',
              status: 'operational',
            },
            {
              id: 'wc-7-1-2',
              workCenterId: 'WC-07-01-02',
              machineName: 'Documentation',
              x: 150,
              y: 1700,
              width: 80,
              height: 80,
              icon: 'file-text',
              status: 'operational',
            },
            {
              id: 'wc-7-1-3',
              workCenterId: 'WC-07-01-03',
              machineName: 'Shipping Prep',
              x: 250,
              y: 1700,
              width: 80,
              height: 80,
              icon: 'truck',
              status: 'operational',
            },
            {
              id: 'wc-7-1-4',
              workCenterId: 'WC-07-01-04',
              machineName: 'Load Dock',
              x: 350,
              y: 1700,
              width: 80,
              height: 80,
              icon: 'package',
              status: 'operational',
            },
          ],
          color: '#DCEDC8',
        },
        {
          id: 'line-7-2',
          lineId: 'LINE-07-02',
          lineName: 'Lot Yard Staging',
          x: 600,
          y: 1700,
          width: 400,
          height: 1200,
          workCenters: [
            {
              id: 'wc-7-2-1',
              workCenterId: 'WC-07-02-01',
              machineName: 'Lot Yard 1',
              x: 600,
              y: 1700,
              width: 150,
              height: 150,
              icon: 'square',
              status: 'operational',
            },
            {
              id: 'wc-7-2-2',
              workCenterId: 'WC-07-02-02',
              machineName: 'Lot Yard 2',
              x: 600,
              y: 1900,
              width: 150,
              height: 150,
              icon: 'square',
              status: 'operational',
            },
            {
              id: 'wc-7-2-3',
              workCenterId: 'WC-07-02-03',
              machineName: 'Lot Yard 3',
              x: 600,
              y: 2100,
              width: 150,
              height: 150,
              icon: 'square',
              status: 'operational',
            },
          ],
          color: '#C8E6C9',
        },
        {
          id: 'line-7-3',
          lineId: 'LINE-07-03',
          lineName: 'Carrier Dock',
          x: 1150,
          y: 1700,
          width: 350,
          height: 1200,
          workCenters: [
            {
              id: 'wc-7-3-1',
              workCenterId: 'WC-07-03-01',
              machineName: 'Truck Scale',
              x: 1150,
              y: 1700,
              width: 100,
              height: 100,
              icon: 'scale',
              status: 'operational',
            },
            {
              id: 'wc-7-3-2',
              workCenterId: 'WC-07-03-02',
              machineName: 'Load Sequence 1',
              x: 1150,
              y: 1850,
              width: 100,
              height: 100,
              icon: 'truck',
              status: 'operational',
            },
            {
              id: 'wc-7-3-3',
              workCenterId: 'WC-07-03-03',
              machineName: 'Load Sequence 2',
              x: 1150,
              y: 2000,
              width: 100,
              height: 100,
              icon: 'truck',
              status: 'operational',
            },
            {
              id: 'wc-7-3-4',
              workCenterId: 'WC-07-03-04',
              machineName: 'Manifest Checker',
              x: 1300,
              y: 1750,
              width: 100,
              height: 100,
              icon: 'clipboard-list',
              status: 'idle',
            },
          ],
          color: '#A5D6A7',
        },
      ],
      buffers: [
        {
          id: 'buf-7-1',
          bufferId: 'BUF-07-01',
          bufferName: 'Final Buffer',
          x: 50,
          y: 1950,
          width: 500,
          height: 300,
          capacity: 500,
          currentLevel: 387,
        },
      ],
      storage: [
        {
          id: 'stor-7-1',
          storageId: 'STOR-07-01',
          storageName: 'Packaging Materials',
          x: 1650,
          y: 1700,
          width: 300,
          height: 400,
          type: 'materials',
        },
      ],
    },
  ],
};

export const defaultConfiguration: Configuration = {
  id: 'config-1',
  version: '1.0.0',
  name: 'Initial Configuration',
  factory: defaultFactory,
  activated: true,
  activatedBy: 'system',
  activatedAt: new Date(),
  createdAt: new Date(),
  updatedAt: new Date(),
};
